# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Feature CI/CD

on:
  push:
    branches: [ feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.3']

    env:
      extensions: bcmath, ctype, fileinfo, intl, json, mbstring, openssl, pdo, tokenizer, xml
      key: cache-v1 # can be any string, change to clear the extension cache.
      ftphost: "ftp://ftpupload.net/dev.tissue.ml/htdocs"
      ftpuser: epiz_25927316
      ftppass: ${{ secrets.FTP_PASS }}
      ftproot: dev.tissue.tk
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v1
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
          tools: php-cs-fixer, phpunit, pecl
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist
      - run: sudo apt-get update
      - run: sudo apt-get install apache2-utils tar
      - name: Print contents
        run: ls -al
      - name: Print current working dir
        run: pwd
      - name: git-ftp push
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ env.ftphost }}
          user: ${{ env.ftpuser }}
          password: ${{ env.ftppass }}
      - run: git config --global user.email "algae1234567890@gmail.com"
      - run: git config --global user.name "misterlobo"
      - run: chmod +x ./scripts/htpasswd.sh
      - name: Create htpasswd file
        run: ./scripts/htpasswd.sh ${{ secrets.AUTH_USER }} ${{ secrets.AUTH_PASS }}
      - run: touch .env
      - name: Generate encryption key
        run: php artisan key:generate
      - run: sed '$ a DB_CONNECTION=mysqldev' .env
      - run: sed '$ a GITHUB_ID="${{ env.DEV_GITHUB_CLIENT_ID }}"' .env
      - run: cat .env
      - name: Export database to file
        run: echo export database
      - run: git status
      - run: git add .
      - run: git commit -m 'ci generated files'
      - name: Print contents
        run: ls -al
      - run: cd vendor
      - name: prep vendor files for upload
        run: git init
      - run: git add .
      - run: git commit -m 'prep vendor files for upload'
      - name: git-ftp upload vendor
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: "ftp://ftpupload.net/dev.tissue.ml/htdocs/vendor"
          user: ${{ env.ftpuser }}
          password: ${{ env.ftppass }}
      - run: cd ..
      - name: Print if workflow finished successfully
        run: echo workflow successful!
